/* AUTH */
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

export const GET_PRESET_MESSAGE = "GET_PRESET_MESSAGE";
export const GET_PRESET_MESSAGE_SUCCESS = "GET_PRESET_MESSAGE_SUCCESS";
export const GET_PRESET_MESSAGE_FAILED = "GET_PRESET_MESSAGE_FAILED";
export const EDIT_PRESET_MESSAGE = "EDIT_PRESET_MESSAGE";
export const EDIT_PRESET_MESSAGE_SUCCESS = "EDIT_PRESET_MESSAGE_SUCCESS";
export const EDIT_PRESET_MESSAGE_FAILED = "EDIT_PRESET_MESSAGE_FAILED";
export const DELETE_PRESET_MESSAGE = "DELETE_PRESET_MESSAGE";
export const DELETE_PRESET_MESSAGE_SUCCESS = "DELETE_PRESET_MESSAGE_SUCCESS";
export const DELETE_PRESET_MESSAGE_FAILED = "DELETE_PRESET_MESSAGE_FAILED";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
