export const GET_ALLOCATE_DATA = "GET_ALLOCATE_DATA";
export const GET_ALLOCATE_DATA_SUCCESS = "GET_ALLOCATE_DATA_SUCCESS";
export const GET_ALLOCATE_DATA_FAILED = "GET_ALLOCATE_DATA_FAILED";

export const GET_ALLOCATE_BY_ID = "GET_ALLOCATE_BY_ID";
export const GET_ALLOCATE_BY_ID_SUCCESS = "GET_ALLOCATE_BY_ID_SUCCESS";
export const GET_ALLOCATE_BY_ID_FAILED = "GET_ALLOCATE_BY_ID_FAILED";

export const POST_ALLOCATION = "POST_ALLOCATION";
export const POST_ALLOCATION_SUCCESS = "POST_ALLOCATION_SUCCESS";
export const POST_ALLOCATION_FAILED = "POST_ALLOCATION_FAILED";

export const PUT_ALLOCATION = "PUT_ALLOCATION";
export const PUT_ALLOCATION_SUCCESS = "PUT_ALLOCATION_SUCCESS";
export const PUT_ALLOCATION_FAILED = "PUT_ALLOCATION_FAILED";

export const TAKE_ALLOCATION_TASKS = "TAKE_ALLOCATION_TASKS";
export const TAKE_ALLOCATION_TASKS_SUCCESS = "TAKE_ALLOCATION_TASKS_SUCCESS";
export const TAKE_ALLOCATION_TASKS_FAILED = "TAKE_ALLOCATION_TASKS_FAILED";

export const CLEAR_ALLOCATION_MESSAGE = "CLEAR_ALLOCATION_MESSAGE";

export const REASSIGN_ALLOCATION_TASK = "REASSIGN_ALLOCATION_TASK";
export const REASSIGN_ALLOCATION_TASK_SUCCESS =
  "REASSIGN_ALLOCATION_TASK_SUCCESS";
export const REASSIGN_ALLOCATION_TASK_FAILED =
  "REASSIGN_ALLOCATION_TASK_FAILED";
