export const GET_VIP_OFFERS = "GET_VIP_OFFERS";
export const GET_VIP_OFFERS_SUCCESS = "GET_VIP_OFFERS_SUCCESS";
export const GET_VIP_OFFERS_FAILED = "GET_VIP_OFFERS_FAILED";
export const CLEAR_VIP_OFFERS_MESSAGE = "CLEAR_VIP_OFFERS_MESSAGE";

export const GET_VIP_ORDERS = "GET_VIP_ORDERS";
export const GET_VIP_ORDERS_SUCCESS = "GET_VIP_ORDERS_SUCCESS";
export const GET_VIP_ORDERS_FAILED = "GET_VIP_ORDERS_FAILED";

export const GET_CURRENT_VIP_REPORT = "GET_CURRENT_VIP_REPORT";
export const GET_CURRENT_VIP_REPORT_SUCCESS = "GET_CURRENT_VIP_REPORT_SUCCESS";
export const GET_CURRENT_VIP_REPORT_FAILED = "GET_CURRENT_VIP_REPORT_FAILED";

export const GET_VIP_PRODS_BY_GAMEID = "GET_VIP_PRODS_BY_GAMEID";
export const GET_VIP_PRODS_BY_GAMEID_SUCCESS =
  "GET_VIP_PRODS_BY_GAMEID_SUCCESS";
export const GET_VIP_PRODS_BY_GAMEID_FAILED = "GET_VIP_PRODS_BY_GAMEID_FAILED";

export const EDIT_VIP_WIRE_REPORT = "EDIT_VIP_WIRE_REPORT";
export const EDIT_VIP_WIRE_REPORT_SUCCESS = "EDIT_VIP_WIRE_REPORT_SUCCESS";
export const EDIT_VIP_WIRE_REPORT_FAILED = "EDIT_VIP_WIRE_REPORT_FAILED";

export const DELETE_VIP_WIRE_REPORT = "DELETE_VIP_WIRE_REPORT";
export const DELETE_VIP_WIRE_REPORT_SUCCESS = "DELETE_VIP_WIRE_REPORT_SUCCESS";
export const DELETE_VIP_WIRE_REPORT_FAILED = "DELETE_VIP_WIRE_REPORT_FAILED";
