export const GET_VIP_OFFERS = "GET_VIP_OFFERS";
export const GET_VIP_OFFERS_SUCCESS = "GET_VIP_OFFERS_SUCCESS";
export const GET_VIP_OFFERS_FAILED = "GET_VIP_OFFERS_FAILED";
export const CLEAR_VIP_OFFERS_MESSAGE = "CLEAR_VIP_OFFERS_MESSAGE";
