export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";

export const UPDATE_QUESTION_TYPE = "UPDATE_QUESTION_TYPE";
export const UPDATE_QUESTION_TYPE_SUCCESS = "UPDATE_QUESTION_TYPE_SUCCESS";
export const UPDATE_QUESTION_TYPE_FAILED = "UPDATE_QUESTION_TYPE_FAILED";

export const UPDATE_QUESTION_STATUS = "UPDATE_QUESTION_STATUS";
export const UPDATE_QUESTION_STATUS_SUCCESS = "UPDATE_QUESTION_STATUS_SUCCESS";
export const UPDATE_QUESTION_STATUS_FAILED = "UPDATE_QUESTION_STATUS_FAILED";

export const GET_TEST_DATA = "GET_TEST_DATA";
export const GET_TEST_DATA_SUCCESS = "GET_TEST_DATA_SUCCESS";
export const GET_TEST_DATA_FAILED = "GET_TEST_DATA_FAILED";

export const GET_OVERVIEW = "GET_OVERVIEW";
export const GET_OVERVIEW_SUCCESS = "GET_OVERVIEW_SUCCESS";
export const GET_OVERVIEW_FAILED = "GET_OVERVIEW_FAILED";

export const GET_CURRENT_QUESTION = "GET_CURRENT_QUESTION";
export const GET_CURRENT_QUESTION_SUCCESS = "GET_CURRENT_QUESTION_SUCCESS";
export const GET_CURRENT_QUESTION_FAILED = "GET_CURRENT_QUESTION_FAILED";

export const ALLOCATE_QUESTION = "ALLOCATE_QUESTION";
export const ALLOCATE_QUESTION_SUCCESS = "ALLOCATE_QUESTION_SUCCESS";
export const ALLOCATE_QUESTION_FAILED = "ALLOCATE_QUESTION_FAILED";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const REPLY_QUESTION = "REPLY_QUESTION";
export const REPLY_QUESTION_SUCCESS = "REPLY_QUESTION_SUCCESS";
export const REPLY_QUESTION_FAILED = "REPLY_QUESTION_FAILED";

export const CLOSE_QUESTION = "CLOSE_QUESTION";
export const CLOSE_QUESTION_SUCCESS = "CLOSE_QUESTION_SUCCESS";
export const CLOSE_QUESTION_FAILED = "CLOSE_QUESTION_FAILED";

export const GET_SERVICE_STATISTICS = "GET_SERVICE_STATISTICS";
export const GET_SERVICE_STATISTICS_SUCCESS = "GET_SERVICE_STATISTICS_SUCCESS";
export const GET_SERVICE_STATISTICS_FAILED = "GET_SERVICE_STATISTICS_FAILED";

export const GET_SERVICE_CONFIG = "GET_SERVICE_CONFIG";
export const GET_SERVICE_CONFIG_SUCCESS = "GET_SERVICE_CONFIG_SUCCESS";

export const GET_QUESTIONS_BY_USER = "GET_QUESTIONS_BY_USER";
export const GET_QUESTIONS_BY_USER_SUCCESS = "GET_QUESTIONS_BY_USER_SUCCESS";
export const GET_QUESTIONS_BY_USER_FAILED = "GET_QUESTIONS_BY_USER_FAILED";

export const FAVORITE_QUESTION_ACTION = "FAVORITE_QUESTION_ACTION";
export const FAVORITE_QUESTION_ACTION_SUCCESS =
  "FAVORITE_QUESTION_ACTION_SUCCESS";
export const FAVORITE_QUESTION_ACTION_FAILED =
  "FAVORITE_QUESTION_ACTION_FAILED";
