export const GET_VIP_DASHBOARD_DATA = "GET_VIP_DASHBOARD_DATA";
export const GET_VIP_DASHBOARD_DATA_SUCCESS = "GET_VIP_DASHBOARD_DATA_SUCCESS";
export const GET_VIP_DASHBOARD_DATA_FAILED = "GET_VIP_DASHBOARD_DATA_FAILED";
