export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USER_TASKS = 'GET_USER_TASKS';
export const GET_USER_TASKS_SUCCESS = 'GET_USER_TASKS_SUCCESS';
export const GET_USER_TASKS_FAILED = 'GET_USER_TASKS_FAILED';

export const GET_USER_LOGS = 'GET_USER_LOGS';
export const GET_USER_LOGS_SUCCESS = 'GET_USER_LOGS_SUCCESS';
export const GET_USER_LOGS_FAILED = 'GET_USER_LOGS_FAILED';
