export const GET_OCSDATA_SUCCESS = 'GET_OCSDATA_SUCCESS';
export const GET_OCSDATA_FAILED = 'GET_OCSDATA_FAILED';
export const ADD_OCSDATA_SUCCESS = 'ADD_OCSDATA_SUCCESS';
export const ADD_OCSDATA_FAILED = 'ADD_OCSDATA_FAILED';
export const LOADING_BEGIN = 'LOADING_BEGIN';
export const LOADING_END = 'LOADING_END';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const GET_CURRENT_RECORD = 'GET_CURRENT_RECORD';
export const CLEAR_CURRENT_RECORD = 'CLEAR_CURRENT_RECORD';
export const GET_CSMASTER_SUCCESS = 'GET_CSMASTER_SUCCESS';
export const GET_CSMASTER_FAILED = 'GET_CSMASTER_FAILED';

export const GET_GOV_DATA = 'GET_GOV_DATA';
export const GET_GOV_DATA_SUCCESS = 'GET_GOV_DATA_SUCCESS';
export const GET_GOV_DATA_FAILED = 'GET_GOV_DATA_FAILED';

export const EDIT_RECORD = 'EDIT_RECORD';
export const EDIT_RECORD_SUCCESS = 'EDIT_RECORD_SUCCESS';
export const EDIT_RECORD_FAILED = 'EDIT_RECORD_FAILED';

export const GET_CURRENT = 'GET_CURRENT';
export const GET_CURRENT_SUCCESS = 'GET_CURRENT_SUCCESS';
export const GET_CURRENT_FAILED = 'GET_CURRENT_FAILED';
