export const GET_OCSDATA_SUCCESS = 'GET_OCSDATA_SUCCESS';
export const GET_OCSDATA_FAILED = 'GET_OCSDATA_FAILED';
export const ADD_OCSDATA_SUCCESS = 'ADD_OCSDATA_SUCCESS';
export const ADD_OCSDATA_FAILED = 'ADD_OCSDATA_FAILED';
export const LOADING_BEGIN = 'LOADING_BEGIN';
export const LOADING_END = 'LOADING_END';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const GET_CURRENT_RECORD = 'GET_CURRENT_RECORD';
export const CLEAR_CURRENT_RECORD = 'CLEAR_CURRENT_RECORD';
export const GET_CSMASTER_SUCCESS = 'GET_CSMASTER_SUCCESS';
export const GET_CSMASTER_FAILED = 'GET_CSMASTER_FAILED';

export const GET_GOV_DATA = 'GET_GOV_DATA';
export const GET_GOV_DATA_SUCCESS = 'GET_GOV_DATA_SUCCESS';
export const GET_GOV_DATA_FAILED = 'GET_GOV_DATA_FAILED';

export const EDIT_RECORD = 'EDIT_RECORD';
export const EDIT_RECORD_SUCCESS = 'EDIT_RECORD_SUCCESS';
export const EDIT_RECORD_FAILED = 'EDIT_RECORD_FAILED';

export const GET_CURRENT = 'GET_CURRENT';
export const GET_CURRENT_SUCCESS = 'GET_CURRENT_SUCCESS';
export const GET_CURRENT_FAILED = 'GET_CURRENT_FAILED';

export const EDIT_CPL_REPLY = 'EDIT_CPL_REPLY';
export const EDIT_CPL_REPLY_SUCCESS = 'EDIT_CPL_REPLY_SUCCESS';
export const EDIT_CPL_REPLY_FAILED = 'EDIT_CPL_REPLY_FAILED';

export const DELETE_CPL = 'DELETE_CPL';
export const DELETE_CPL_SUCCESS = 'DELETE_CPL_SUCCESS';
export const DELETE_CPL_FAILED = 'DELETE_CPL_FAILED';

export const MOVE_CPL = 'MOVE_CPL';
export const MOVE_CPL_SUCCESS = 'MOVE_CPL_SUCCESS';
export const MOVE_CPL_FAILED = 'MOVE_CPL_FAILED';

export const EDIT_CPL_MEDIATION = 'EDIT_CPL_MEDIATION';
export const EDIT_CPL_MEDIATION_SUCCESS = 'EDIT_CPL_MEDIATION_SUCCESS';
export const EDIT_CPL_MEDIATION_FAILED = 'EDIT_CPL_MEDIATION_FAILED';

export const DELETE_CPL_REPLY = 'DELETE_CPL_REPLY';
export const DELETE_CPL_REPLY_SUCCESS = 'DELETE_CPL_REPLY_SUCCESS';
export const DELETE_CPL_REPLY_FAILED = 'DELETE_CPL_REPLY_FAILED';

export const DELETE_CPL_MEDIATION = 'DELETE_CPL_MEDIATION';
export const DELETE_CPL_MEDIATION_SUCCESS = 'DELETE_CPL_MEDIATION_SUCCESS';
export const DELETE_CPL_MEDIATION_FAILED = 'DELETE_CPL_MEDIATION_FAILED';

export const EDIT_CPL_REF = 'EDIT_CPL_REF';
export const EDIT_CPL_REF_SUCCESS = 'EDIT_CPL_REF_SUCCESS';
export const EDIT_CPL_REF_FAILED = 'EDIT_CPL_REF_FAILED';
export const DELETE_CPL_REF = 'DELETE_CPL_REF';
export const DELETE_CPL_REF_SUCCESS = 'DELETE_CPL_REF_SUCCESS';
export const DELETE_CPL_REF_FAILED = 'DELETE_CPL_REF_FAILED';

export const ADD_CPL_ATTACHMENT = 'ADD_CPL_ATTACHMENT';
export const ADD_CPL_ATTACHMENT_SUCCESS = 'ADD_CPL_ATTACHMENT_SUCCESS';
export const ADD_CPL_ATTACHMENT_FAILED = 'ADD_CPL_ATTACHMENT_FAILED';

export const DELETE_CPL_ATTACHMENT = 'DELETE_CPL_ATTACHMENT';
export const DELETE_CPL_ATTACHMENT_SUCCESS = 'DELETE_CPL_ATTACHMENT_SUCCESS';
export const DELETE_CPL_ATTACHMENT_FAILED = 'DELETE_CPL_ATTACHMENT_FAILED';

export const DELETE_GOV_LETTER = 'DELETE_GOV_LETTER';
export const DELETE_GOV_LETTER_SUCCESS = 'DELETE_GOV_LETTER_SUCCESS';
export const DELETE_GOV_LETTER_FAILED = 'DELETE_GOV_LETTER_FAILED';
