export const GET_GAMES_DATA_SUCCESS = "GET_GAMES_DATA_SUCCESS";
export const GET_GAMES_DATA_FAILED = "GET_GAMES_DATA_FAILED";
export const GET_GAMES_DATA = "GET_GAMES_DATA";

export const EDIT_GAME = "EDIT_GAME";
export const EDIT_GAME_SUCCESS = "EDIT_GAME_SUCCESS";
export const EDIT_GAME_FAILED = "EDIT_GAME_FAILED";

export const GET_CURRENT_GAME = "GET_CURRENT_GAME";
export const GET_CURRENT_GAME_SUCCESS = "GET_CURRENT_GAME_SUCCESS";
export const GET_CURRENT_GAME_FAILED = "GET_CURRENT_GAME_FAILED";

export const CLEAR_CURRENT_GAME = "CLEAR_CURRENT_GAME";
