export const GET_BATCH_TASKS = "GET_BATCH_TASKS";
export const GET_BATCH_TASKS_SUCCESS = "GET_BATCH_TASKS_SUCCESS";
export const GET_BATCH_TASKS_FAILED = "GET_BATCH_TASKS_FAILED";

export const EDIT_BATCH_TASK = "EDIT_BATCH_TASK";
export const EDIT_BATCH_TASK_SUCCESS = "EDIT_BATCH_TASK_SUCCESS";
export const EDIT_BATCH_TASK_FAILED = "EDIT_BATCH_TASK_FAILED";
export const DELETE_BATCH_TASK = "DELETE_BATCH_TASK";
export const DELETE_BATCH_TASK_SUCCESS = "DELETE_BATCH_TASK_SUCCESS";
export const DELETE_BATCH_TASK_FAILED = "DELETE_BATCH_TASK_FAILED";

export const CLEAR_BATCH_TASK_MESSAGE = "CLEAR_BATCH_TASK_MESSAGE";

export const GET_CURRENT_BATCH_TASK = "GET_CURRENT_BATCH_TASK";
export const GET_CURRENT_BATCH_TASK_SUCCESS = "GET_CURRENT_BATCH_TASK_SUCCESS";
export const GET_CURRENT_BATCH_TASK_FAILED = "GET_CURRENT_BATCH_TASK_FAILED";

export const REMOVE_BATCH_Q = "REMOVE_BATCH_Q";
export const REMOVE_BATCH_Q_SUCCESS = "REMOVE_BATCH_Q_SUCCESS";
export const REMOVE_BATCH_Q_FAILED = "REMOVE_BATCH_Q_FAILED";
export const REMOVE_Q_FROM_BATCH = "REMOVE_Q_FROM_BATCH";
export const REMOVE_Q_FROM_BATCH_SUCCESS = "REMOVE_Q_FROM_BATCH_SUCCESS";
export const REMOVE_Q_FROM_BATCH_FAILED = "REMOVE_Q_FROM_BATCH_FAILED";

export const BATCH_REPLY_ACTION = "BATCH_REPLY_ACTION";
export const BATCH_REPLY_ACTION_SUCCESS = "BATCH_REPLY_ACTION_SUCCESS";
export const BATCH_REPLY_ACTION_FAILED = "BATCH_REPLY_ACTION_FAILED";
