export const GET_VIP_GAMES = "GET_VIP_GAMES";
export const GET_VIP_GAMES_SUCCESS = "GET_VIP_GAMES_SUCCESS";
export const GET_VIP_GAMES_FAILED = "GET_VIP_GAMES_FAILED";

export const GET_VIP = "GET_VIP";
export const GET_VIP_SUCCESS = "GET_VIP_SUCCESS";
export const GET_VIP_FAILED = "GET_VIP_FAILED";

export const UPDATE_VIP_STATUS = "UPDATE_VIP_STATUS";
export const UPDATE_VIP_STATUS_SUCCESS = "UPDATE_VIP_STATUS_SUCCESS";
export const UPDATE_VIP_STATUS_FAILED = "UPDATE_VIP_STATUS_FAILED";

export const CLEAR_VIP_MESSAGE = "CLEAR_VIP_MESSAGE";

export const DELETE_VIP_REQUEST = "DELETE_VIP_REQUEST";
export const DELETE_VIP_REQUEST_SUCCESS = "DELETE_VIP_REQUEST_SUCCESS";
export const DELETE_VIP_REQUEST_FAILED = "DELETE_VIP_REQUEST_FAILED";

export const ADD_VIP_REQUEST = "ADD_VIP_REQUEST";
export const ADD_VIP_REQUEST_SUCCESS = "ADD_VIP_REQUEST_SUCCESS";
export const ADD_VIP_REQUEST_FAILED = "ADD_VIP_REQUEST_FAILED";
export const ADD_VIP_REQUEST_VALIDATION_FAILED =
  "ADD_VIP_REQUEST_VALIDATION_FAILED";

export const GET_CURRENT_WHALE_USER = "GET_CURRENT_WHALE_USER";
export const GET_CURRENT_WHALE_USER_SUCCESS = "GET_CURRENT_WHALE_USER_SUCCESS";
export const GET_CURRENT_WHALE_USER_FAILED = "GET_CURRENT_WHALE_USER_FAILED";

export const UPDATE_VIP_INFO = "UPDATE_VIP_INFO";
export const UPDATE_VIP_INFO_SUCCESS = "UPDATE_VIP_INFO_SUCCESS";
export const UPDATE_VIP_INFO_FAILED = "UPDATE_VIP_INFO_FAILED";

export const GET_VIP_REQUESTS = "GET_VIP_REQUESTS";
export const GET_VIP_REQUESTS_SUCCESS = "GET_VIP_REQUESTS_SUCCESS";
export const GET_VIP_REQUESTS_FAILED = "GET_VIP_REQUESTS_FAILED";
